#!/usr/bin/env bash

# e.g. https://grpc-gateway-go-sandbox-xxxxxx-an.a.run.app
ENDPOINT=$1

echo $ENDPOINT

curl -X GET "${ENDPOINT}/api/v1/users" -H "accept: application/json"

curl -X POST "${ENDPOINT}/api/v1/users" -H "accept: application/json" -H "Content-Type: application/json" -d "{}"
